name: release-please
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple

  deploy:
    needs: release
    runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.release_created }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Set environment variable
        run: echo "GAME=${{ github.event.repository.name }}.love" >> $GITHUB_ENV

      - name: Build
        run: |
          shopt -s globstar && zip -9 -r $GAME **/*.lua assets
          npx love.js $GAME web -c -t "Love Template"

      - name: Setup butler
        uses: remarkablegames/setup-butler@v1

      - name: Upload to itch.io
        run: |
          for i in "web web" "$GAME love"
          do
            set -- $i
            butler push $1 ${{ github.repository }}:$2 --userversion-file version.txt
          done
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

      - name: Upload Release Artifact
        run: gh release upload ${{ needs.release.outputs.tag_name }} $GAME
        env:
          GH_TOKEN: ${{ github.token }}
